In [1]:
import numpy as np
import pandas as pd

In [31]:
data = pd.read_csv('Data/Bin Locations.csv', index_col= 'id').sort_index()
distance = pd.read_csv('Data/distance.csv').drop('Unnamed: 0', axis=1)

In [35]:
distance

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,300
0,0.0,10920.9,7289.7,6487.3,13930.6,14243.4,9381.6,11159.2,17208.6,9012.4,...,13649.9,7762.0,10788.5,7715.3,7370.2,10465.4,10536.4,11995.5,11737.5,10121.1
1,10920.9,0.0,4768.5,6527.9,0.0,0.0,0.0,0.0,0.0,3310.4,...,0.0,0.0,0.0,0.0,4388.8,0.0,0.0,0.0,0.0,0.0
2,7289.7,4768.5,0.0,5586.7,0.0,0.0,0.0,0.0,0.0,4581.8,...,0.0,0.0,0.0,0.0,3091.0,0.0,0.0,0.0,0.0,0.0
3,6487.3,6527.9,5586.7,0.0,0.0,0.0,0.0,0.0,0.0,4407.9,...,0.0,0.0,0.0,0.0,5163.1,0.0,0.0,0.0,0.0,0.0
4,13930.6,0.0,0.0,0.0,0.0,0.0,4931.3,2942.0,0.0,0.0,...,0.0,6349.7,5497.9,7443.6,0.0,4407.9,3630.6,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,10465.4,0.0,0.0,0.0,4407.9,0.0,2028.3,5711.3,0.0,0.0,...,0.0,5913.9,6629.4,9147.1,0.0,0.0,5086.8,0.0,0.0,0.0
297,10536.4,0.0,0.0,0.0,3630.6,0.0,3982.4,957.0,0.0,0.0,...,0.0,3011.0,1665.2,4182.8,0.0,5086.8,0.0,0.0,0.0,0.0
298,11995.5,0.0,0.0,0.0,0.0,3171.6,0.0,0.0,6643.0,0.0,...,3185.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,355.4,3247.8
299,11737.5,0.0,0.0,0.0,0.0,3623.2,0.0,0.0,7094.6,0.0,...,3637.2,0.0,0.0,0.0,0.0,0.0,0.0,355.4,0.0,3253.8
300,10121.1,0.0,0.0,0.0,0.0,4657.8,0.0,0.0,8129.2,0.0,...,4671.8,0.0,0.0,0.0,0.0,0.0,0.0,3247.8,3253.8,0.0